USE ecocoleta;

ALTER TABLE usuario ADD COLUMN foto_perfil VARCHAR(500) NULL DEFAULT NULL;
ALTER TABLE usuario ADD COLUMN numero VARCHAR(30) NULL DEFAULT NULL;
ALTER TABLE usuario ADD COLUMN cidade VARCHAR(120) NULL DEFAULT NULL;
ALTER TABLE usuario ADD COLUMN complemento VARCHAR(200) NULL DEFAULT NULL;
ALTER TABLE usuario ADD COLUMN cep VARCHAR(10) NULL DEFAULT NULL;
