<?php

return [
    [
        "id_agendamento" => 9001,
        "usuario" => "Aurélio de Carvalho",
        "nome_ecoponto" => "EcoPonto Juazeiro Centro",
        "bairro" => "Santa Rosa",
        "data_coleta" => "2026-11-07",
        "slot_ordem" => 1,
        "horario_solicitacao" => "07/11/2026 - 09:00h",
        "responsavel" => "Caminhão - Prefeitura",
        "status" => "concluida",
        "tipo" => "caminhao",
    ],
    [
        "id_agendamento" => 9002,
        "usuario" => "Aurélio de Carvalho",
        "bairro" => "Santa Tereza",
        "data_coleta" => "2026-11-07",
        "slot_ordem" => 1,
        "horario_solicitacao" => "07/11/2026 - 09:30h",
        "responsavel" => "Coleta Alternativa",
        "status" => "cancelado",
        "tipo" => "prefeitura",
    ],
    [
        "id_agendamento" => 9003,
        "usuario" => "Aurélio de Carvalho",
        "nome_ecoponto" => "EcoPonto Lagoa Seca",
        "bairro" => "Lagoa Seca",
        "data_coleta" => "2026-11-07",
        "slot_ordem" => 0,
        "horario_solicitacao" => "07/11/2026 - 09:00h",
        "responsavel" => "Equipe Caminhão - 01",
        "status" => "andamento",
        "tipo" => "caminhao",
    ],
    [
        "id_agendamento" => 9004,
        "usuario" => "Mariana Silva",
        "nome_ecoponto" => "EcoPonto Juazeiro Centro",
        "bairro" => "Triângulo",
        "data_coleta" => "2026-11-08",
        "slot_ordem" => 2,
        "horario_solicitacao" => "08/11/2026 - 13:00h",
        "responsavel" => "Caminhão - Prefeitura",
        "status" => "confirmado",
        "tipo" => "caminhao",
    ],
    [
        "id_agendamento" => 9005,
        "usuario" => "Carlos Mendes",
        "nome_ecoponto" => "EcoPonto Crato Centro",
        "bairro" => "Centro",
        "data_coleta" => "2026-11-08",
        "slot_ordem" => 0,
        "horario_solicitacao" => "08/11/2026 - 07:00h",
        "responsavel" => "Equipe Caminhão - 02",
        "status" => "andamento",
        "tipo" => "caminhao",
    ],
    [
        "id_agendamento" => 9006,
        "usuario" => "Ana Paula Rocha",
        "bairro" => "Pirajá",
        "data_coleta" => "2026-11-09",
        "slot_ordem" => 1,
        "horario_solicitacao" => "09/11/2026 - 10:00h",
        "responsavel" => "Coleta Alternativa",
        "status" => "concluida",
        "tipo" => "prefeitura",
    ],
    [
        "id_agendamento" => 9007,
        "usuario" => "João Pedro Lima",
        "nome_ecoponto" => "EcoPonto Seminário",
        "bairro" => "Seminário",
        "data_coleta" => "2026-11-09",
        "slot_ordem" => 2,
        "horario_solicitacao" => "09/11/2026 - 13:00h",
        "responsavel" => "Caminhão - Prefeitura",
        "status" => "cancelado",
        "tipo" => "caminhao",
    ],
    [
        "id_agendamento" => 9008,
        "usuario" => "Fernanda Costa",
        "nome_ecoponto" => "EcoPonto Parque da Cidade",
        "bairro" => "Parque da Cidade",
        "data_coleta" => "2026-11-10",
        "slot_ordem" => 0,
        "horario_solicitacao" => "10/11/2026 - 07:00h",
        "responsavel" => "Equipe Caminhão - 01",
        "status" => "confirmado",
        "tipo" => "caminhao",
    ],
    [
        "id_agendamento" => 9009,
        "usuario" => "Ricardo Alves",
        "nome_ecoponto" => "EcoPonto Barbalha Centro",
        "bairro" => "Belavista",
        "data_coleta" => "2026-11-10",
        "slot_ordem" => 3,
        "horario_solicitacao" => "10/11/2026 - 16:00h",
        "responsavel" => "Caminhão - Prefeitura",
        "status" => "concluida",
        "tipo" => "caminhao",
    ],
    [
        "id_agendamento" => 9010,
        "usuario" => "Patrícia Nunes",
        "bairro" => "Rio Baixo",
        "data_coleta" => "2026-11-11",
        "slot_ordem" => 1,
        "horario_solicitacao" => "11/11/2026 - 10:00h",
        "responsavel" => "Coleta Alternativa",
        "status" => "andamento",
        "tipo" => "prefeitura",
    ],
    [
        "id_agendamento" => 9011,
        "usuario" => "Lucas Ferreira",
        "nome_ecoponto" => "EcoPonto Missão Velha Centro",
        "bairro" => "Vila Central",
        "data_coleta" => "2026-11-11",
        "slot_ordem" => 2,
        "horario_solicitacao" => "11/11/2026 - 13:00h",
        "responsavel" => "Equipe Caminhão - 03",
        "status" => "confirmado",
        "tipo" => "caminhao",
    ],
    [
        "id_agendamento" => 9012,
        "usuario" => "Beatriz Santos",
        "nome_ecoponto" => "EcoPonto Juazeiro Centro",
        "bairro" => "Centro",
        "data_coleta" => "2026-11-12",
        "slot_ordem" => 0,
        "horario_solicitacao" => "12/11/2026 - 07:00h",
        "responsavel" => "Caminhão - Prefeitura",
        "status" => "concluida",
        "tipo" => "caminhao",
    ],
];
