<?php

return [
    "kpis" => [
        "coletas" => 8542,
        "usuarios_ativos" => 1245,
        "kg_reciclaveis" => 255,
        "taxa_reciclagem" => 66,
    ],
    "materiais" => [
        "labels" => ["Plástico", "Papel", "Vidro", "Metal", "Orgânico"],
        "values" => [120, 85, 65, 50, 95],
        "colors" => ["#0f6b38", "#12895d", "#5eb8d4", "#8a9ba8", "#7a8f3e"],
    ],
    "ruas" => [
        ["nome" => "Av. Padre Cícero", "pct" => 27, "cor" => "#0f6b38"],
        ["nome" => "Rua São Pedro", "pct" => 20, "cor" => "#12895d"],
        ["nome" => "Rua Franklin Távora", "pct" => 15, "cor" => "#5eb8d4"],
        ["nome" => "Rua Catulo da Paixão Cearense", "pct" => 12, "cor" => "#8a9ba8"],
        ["nome" => "Rua Pirajá", "pct" => 10, "cor" => "#7a8f3e"],
        ["nome" => "Rua Mestre Vitalino", "pct" => 16, "cor" => "#2dd4a8"],
    ],
    "agendamentos" => [
        [
            "id_agendamento" => 1024,
            "id" => "#1024",
            "usuario" => "Mariana Silva",
            "data" => "02/06/2026",
            "data_coleta" => "2026-06-02",
            "ecoponto" => "EcoPonto Centro",
            "bairro" => "Centro",
            "status" => "confirmado",
            "status_db" => "confirmado",
            "slot_ordem" => 1,
            "tipo" => "caminhao",
            "responsavel" => "Caminhão - Prefeitura",
        ],
        [
            "id_agendamento" => 1023,
            "id" => "#1023",
            "usuario" => "Carlos Mendes",
            "data" => "02/06/2026",
            "data_coleta" => "2026-06-02",
            "ecoponto" => "EcoPonto Vila Verde",
            "bairro" => "Triângulo",
            "status" => "andamento",
            "status_db" => "andamento",
            "slot_ordem" => 2,
            "tipo" => "caminhao",
            "responsavel" => "Equipe Caminhão - 01",
        ],
        [
            "id_agendamento" => 1022,
            "id" => "#1022",
            "usuario" => "Ana Paula",
            "data" => "01/06/2026",
            "data_coleta" => "2026-06-01",
            "ecoponto" => "EcoPonto Belavista",
            "bairro" => "Pirajá",
            "status" => "coletado",
            "status_db" => "concluida",
            "slot_ordem" => 0,
            "tipo" => "prefeitura",
            "responsavel" => "Coleta Alternativa",
        ],
    ],
    "meta" => ["fonte" => "demo"],
];
