<?php

return [
    [
        "id" => "juazeiro-centro",
        "name" => "EcoPonto Verde",
        "address" => "Centro, Juazeiro do Norte",
        "city" => "Juazeiro do Norte",
        "lat" => -7.2127,
        "lng" => -39.3155,
        "bairro" => "Centro",
        "status" => "ativo",
        "capacidade" => 72,
        "responsavel" => "Mariana Silva",
    ],
    [
        "id" => "juazeiro-lagoa-seca",
        "name" => "Ponto Verde Sustentável",
        "address" => "Lagoa Seca, Juazeiro do Norte",
        "city" => "Juazeiro do Norte",
        "lat" => -7.2468,
        "lng" => -39.3042,
        "bairro" => "Lagoa Seca",
        "status" => "ativo",
        "capacidade" => 68,
        "responsavel" => "Carlos Mendes",
    ],
    [
        "id" => "juazeiro-piraja",
        "name" => "ReciclaJá",
        "address" => "Pirajá, Juazeiro do Norte",
        "city" => "Juazeiro do Norte",
        "lat" => -7.1972,
        "lng" => -39.3238,
        "bairro" => "Pirajá",
        "status" => "ativo",
        "capacidade" => 84,
        "responsavel" => "Ana Paula Rocha",
    ],
    [
        "id" => "crato-centro",
        "name" => "Centro de Reciclagem Ambiental",
        "address" => "Centro, Crato",
        "city" => "Crato",
        "lat" => -7.2343,
        "lng" => -39.4097,
        "bairro" => "Centro",
        "status" => "ativo",
        "capacidade" => 78,
        "responsavel" => "João Pedro Lima",
    ],
    [
        "id" => "crato-seminario",
        "name" => "Espaço EcoVida",
        "address" => "Seminário, Crato",
        "city" => "Crato",
        "lat" => -7.2267,
        "lng" => -39.4275,
        "bairro" => "Seminário",
        "status" => "ativo",
        "capacidade" => 45,
        "responsavel" => "Fernanda Costa",
    ],
    [
        "id" => "barbalha-centro",
        "name" => "Estação de Reciclagem",
        "address" => "Centro, Barbalha",
        "city" => "Barbalha",
        "lat" => -7.3124,
        "lng" => -39.3049,
        "bairro" => "Centro",
        "status" => "ativo",
        "capacidade" => 88,
        "responsavel" => "Ricardo Alves",
    ],
    [
        "id" => "barbalha-parque",
        "name" => "Núcleo de Coleta Sustentável",
        "address" => "Parque da Cidade, Barbalha",
        "city" => "Barbalha",
        "lat" => -7.2998,
        "lng" => -39.2926,
        "bairro" => "Parque da Cidade",
        "status" => "ativo",
        "capacidade" => 52,
        "responsavel" => "Patrícia Nunes",
    ],
    [
        "id" => "missao-velha-centro",
        "name" => "PEV Verde",
        "address" => "Centro, Missão Velha",
        "city" => "Missão Velha",
        "lat" => -7.2497,
        "lng" => -39.1437,
        "bairro" => "Centro",
        "status" => "ativo",
        "capacidade" => 76,
        "responsavel" => "Lucas Ferreira",
    ],
    [
        "id" => "caririacu-centro",
        "name" => "EcoCentro Comunitário",
        "address" => "Centro, Caririaçu",
        "city" => "Caririaçu",
        "lat" => -7.0428,
        "lng" => -39.2848,
        "bairro" => "Centro",
        "status" => "ativo",
        "capacidade" => 63,
        "responsavel" => "Mariana Silva",
    ],
    [
        "id" => "jardim-centro",
        "name" => "Planeta Verde",
        "address" => "Centro, Jardim",
        "city" => "Jardim",
        "lat" => -7.5755,
        "lng" => -39.2826,
        "bairro" => "Centro",
        "status" => "ativo",
        "capacidade" => 70,
        "responsavel" => "Carlos Mendes",
    ],
    [
        "id" => "milagres-centro",
        "name" => "EcoFuturo",
        "address" => "Centro, Milagres",
        "city" => "Milagres",
        "lat" => -7.3138,
        "lng" => -38.9458,
        "bairro" => "Centro",
        "status" => "ativo",
        "capacidade" => 82,
        "responsavel" => "Ana Paula Rocha",
    ],
    [
        "id" => "nova-olinda-centro",
        "name" => "Recicle-se",
        "address" => "Centro, Nova Olinda",
        "city" => "Nova Olinda",
        "lat" => -7.0866,
        "lng" => -39.6803,
        "bairro" => "Centro",
        "status" => "ativo",
        "capacidade" => 58,
        "responsavel" => "João Pedro Lima",
    ],
    [
        "id" => "santana-cariri-centro",
        "name" => "EcoAção",
        "address" => "Centro, Santana do Cariri",
        "city" => "Santana do Cariri",
        "lat" => -7.1774,
        "lng" => -39.7371,
        "bairro" => "Centro",
        "status" => "ativo",
        "capacidade" => 91,
        "responsavel" => "Fernanda Costa",
    ],
    [
        "id" => "farias-brito-centro",
        "name" => "Verdejando",
        "address" => "Centro, Farias Brito",
        "city" => "Farias Brito",
        "lat" => -6.9308,
        "lng" => -39.5656,
        "bairro" => "Centro",
        "status" => "ativo",
        "capacidade" => 61,
        "responsavel" => "Ricardo Alves",
    ],
    [
        "id" => "brejo-santo-centro",
        "name" => "EcoVibe",
        "address" => "Centro, Brejo Santo",
        "city" => "Brejo Santo",
        "lat" => -7.4929,
        "lng" => -38.9877,
        "bairro" => "Centro",
        "status" => "ativo",
        "capacidade" => 66,
        "responsavel" => "Patrícia Nunes",
    ],
];
